apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    # ⚠️ THAY ĐỔI URL REPO CỦA BẠN TẠI ĐÂY
    repoURL: https://github.com/<YOUR_USERNAME>/argocd-demo-app.git
    targetRevision: HEAD
    path: manifests/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
